plugins {
	id 'io.github.brainage04.client-gametest-recorder' version "${fabricmoddingconventions_version}"
	id 'io.github.brainage04.production-gametests' version "${fabricmoddingconventions_version}"
	id 'io.github.brainage04.workspace-dependencies' version "${fabricmoddingconventions_version}"
	id 'io.github.brainage04.mod-publishing' version "${fabricmoddingconventions_version}"
}

repositories {
	mavenLocal()
	maven { url "https://maven.nucleoid.xyz/" }
}

dependencies {
	implementation "eu.pb4:polymer-core:${project.polymer_version}"
	include "eu.pb4:polymer-bundled:${project.polymer_version}"
}

workspaceDependencies {
	siblingMaven("FabricModdingConventions") {
		coordinate.set("io.github.brainage04:fabricmoddingconventions:${project.fabricmoddingconventions_version}")
	}
}

fabricApi {
	configureDataGeneration {
		client = false
	}
}

pluginManager.withPlugin("io.github.brainage04.client-gametest-recorder") {
	clientGameTestRecorder {
		guiScale.set("3")
	}
}
