# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.vfs.watch=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
java_version=25
architectury_loom_version=1.17.491
neoforge_version=26.2.0.41-beta

# Mod Properties
mod_side=server
mod_version=1.0.0
mod_id=procedural_dungeon
maven_group=com.github.brainage04.procedural_dungeon
archives_base_name=procedural_dungeon
mod_name=ProceduralDungeon

# Dependencies
fabric_api_version=0.156.0+26.2
fabricmoddingconventions_version=2.4.12
