plugins {
    id 'dev.architectury.loom-no-remap'
    id 'dev.architectury.loom'
}
sourceSets {
    main {
        resources.srcDir project.file('src/main/generated')
        resources.exclude '.cache/**'
    }
}
loom { accessWidenerPath = project(':fabric').file('src/main/resources/procedural_dungeon.accesswidener') }
dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    compileOnly "net.fabricmc:fabric-loader:${rootProject.loader_version}"
    compileOnly "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
}
